metadata: {}
pipelines:
  blis:
    envs:
    - host
    path: pipelines/blis
    stages:
    - build-docker-image
    - run
    - analyze
    - validate
  chameleon-benchmarking:
    envs:
    - host
    path: pipelines/chameleon-benchmarking
    stages:
    - setup.sh
    - run.sh
    - teardown.sh
  cloudlab-benchmarking:
    envs:
    - host
    path: pipelines/cloudlab-benchmarking
    stages:
    - setup.sh
    - run.sh
    - teardown.sh
  data-world:
    envs:
    - host
    path: pipelines/data-world
    stages:
    - run
    - update-data-world-repo
  datapackage:
    envs:
    - host
    path: pipelines/datapackage
    stages:
    - run.sh
    - update-datapackage.sh
  docker-data-science:
    envs:
    - host
    path: pipelines/docker-data-science
    stages:
    - setup
    - analyze
    - generate-figures
  envvar-param:
    envs:
    - host
    path: pipelines/envvar-param
    stages:
    - run
  gce-benchmarking:
    envs:
    - host
    path: pipelines/gce-benchmarking
    stages:
    - setup.sh
    - run.sh
    - teardown.sh
  genomics:
    envs:
    - host
    path: pipelines/genomics
    stages:
    - setup.sh
    - run.sh
    - post-run.sh
    - concordance.sh
    - validate.sh
    - teardown.sh
  perihelion-mercury:
    envs:
    - host
    path: pipelines/perihelion-mercury
    requirements: {}
    stages:
    - setup
    - run
    vars: []
  pgbench:
    envs:
    - host
    path: pipelines/pgbench
    stages:
    - setup
    - run
    - cleanup
    - analyze
  pypet-brian2:
    envs:
      host:
        args: []
    path: pipelines/pypet-brian2
    requirements:
      bin:
      - virtualenv
      - python
      - pip
      vars: []
    stages:
    - setup
    - run
    - post-run
    - validate
    - teardown
    vars: []
  sea-surface-mapping-r:
    envs:
    - host
    path: pipelines/sea-surface-mapping-r
    stages:
    - setup.sh
    - run.sh
  vagrant-linux:
    envs:
    - host
    path: pipelines/vagrant-linux
    stages:
    - init
    - build-kernel
    - deploy-kernel
    - run
    - visualize
  validator:
    envs:
    - host
    path: pipelines/validator
    stages:
    - virtual-environment-checker.sh
    - generate-data.sh
    - validate.sh
popperized:
- github/popperized
