metadata: {}
pipelines:
  blis:
    envs:
    - host
    path: pipelines/blis
    stages:
    - run
  cloudlab-benchmarking:
    envs:
    - host
    path: pipelines/cloudlab-benchmarking
    stages:
    - setup.sh
    - run.sh
    - teardown.sh
  data-world:
    envs:
    - host
    path: pipelines/data-world
    stages:
    - run
    - update-data-world-repo
  datapackage:
    envs:
    - host
    path: pipelines/datapackage
    stages:
    - run.sh
    - update-datapackage.sh
  docker-data-science:
    envs:
    - host
    path: pipelines/docker-data-science
    stages:
    - setup
    - analyze
    - generate-figures
  envvar-param:
    envs:
    - host
    path: pipelines/envvar-param
    stages:
    - run
  genomics:
    envs:
    - host
    path: pipelines/genomics
    stages:
    - setup.sh
    - run.sh
    - post-run.sh
    - concordance.sh
    - validate.sh
    - teardown.sh
  pgbench:
    envs:
    - host
    path: pipelines/pgbench
    stages:
    - setup
    - run
    - cleanup
    - analyze
  sea-surface-mapping-r:
    envs:
    - host
    path: pipelines/sea-surface-mapping-r
    stages:
    - setup
    - run
    vars: []
  vagrant-linux:
    envs:
    - host
    path: pipelines/vagrant-linux
    stages:
    - init
    - build-kernel
    - deploy-kernel
    - run
    - visualize
  validator:
    envs:
    - host
    path: pipelines/validator
    stages:
    - virtual-environment-checker.sh
    - generate-data.sh
    - validate.sh
popperized:
- github/popperized
