metadata: {}
pipelines:
  blis:
    envs:
    - host
    path: pipelines/blis
    stages:
    - run
  data-world:
    envs:
    - host
    path: pipelines/data-world
    stages:
    - run
    - update-data-world-repo
  datapackage:
    envs:
    - host
    path: pipelines/datapackage
    stages:
    - run.sh
    - update-datapackage.sh
  docker-data-science:
    envs:
    - host
    path: pipelines/docker-data-science
    stages:
    - setup
    - analyze
    - generate-figures
  envvar-param:
    envs:
    - host
    path: pipelines/envvar-param
    stages:
    - run
  validator:
    envs:
    - host
    path: pipelines/validator
    stages:
    - virtual-environment-checker.sh
    - generate-data.sh
    - validate.sh
  pgbench:
    envs:
    - host
    path: pipelines/pgbench
    stages:
    - setup
    - run
    - cleanup
    - analyze
popperized:
- github/popperized
