metadata: {}
pipelines:
  blis:
    envs:
    - host
    path: pipelines/blis
    stages:
    - run
  data-world:
    envs:
    - host
    path: pipelines/data-world
    stages:
    - run
    - update-data-world-repo
  datapackage:
    envs:
    - host
    path: pipelines/datapackage
    stages:
    - run
    - update-datapackage
  docker-data-science:
    envs:
    - host
    path: pipelines/docker-data-science
    stages:
    - setup
    - analyze
    - generate-figures
  envvar-param:
    envs:
    - host
    path: pipelines/envvar-param
    stages:
    - run
popperized:
- github/popperized
