# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "debian/stretch64"

  # Enable provisioning with a shell script.
  config.vm.provision "docker"
  config.vm.provision "shell", inline: <<-SHELL
    sudo apt install libelf-dev
    sudo dpkg -i /vagrant/debs/*.deb
  SHELL


  config.vm.synced_folder '../results/', '/home/vagrant/results', id: 'results-dir', owner: "vagrant",
       group: "www-data",
       type: ""
end
