#!/bin/bash
set -e

CREDENTIAL_DIR=${CREDENTIAL_DIR:-$PWD/credentials}
SSH_USER=${SSH_USER:-popper}
SSH_PUB_KEY_FILE=${SSH_PUB_KEY_FILE:-id_rsa.pub}
SSH_KEY_FILE=${SSH_KEY_FILE:-id_rsa}
GCE_IMAGE=${GCE_IMAGE:-debian-9}
GCE_SERVICE_ACCOUNT=${GCE_SERVICE_ACCOUNT:-account.json}

