- hosts: all
  roles:
  - { role: geerlingguy.docker }
- hosts: master
  tasks:
  - name: run spark master
    shell: >
      docker run
      --net=host
      -h spark-master
      -e ENABLE_INIT_DAEMON=false
      -d
      popperized/spark-master

- hosts: workers
  tasks:
  - name: run spark worker
    shell: >
      docker run
      --net=host
      -e ENABLE_INIT_DAEMON=false
      -e SPARK_MASTER='spark://{{ hostvars[groups["master"][0]]["ansible_default_ipv4"]["address"] }}:7077'
      -d
      popperized/spark-worker
- hosts: master
  tasks:
  - name: run benchmark
    shell: >
      docker run --rm
      --net=host
      -e SPARK_MASTER_HOST='spark://{{ hostvars[groups["master"][0]]["ansible_default_ipv4"]["address"] }}:7077'
      -v $PWD:$PWD
      --entrypoint=/spark-bench/bin/spark-bench.sh
      popperized/spark-master /spark-bench/minimal.conf