- hosts: all
  roles:
  - { role: geerlingguy.docker }
- hosts: master
  tasks:
  - name: run spark master
    shell: >
      docker run --name spark-master
      -p 7077:7077 -p 8080:8080
      -h spark-master
      -e ENABLE_INIT_DAEMON=false
      -d
      popperized/spark-master

- hosts: workers
  tasks:
  - name: run spark worker
    shell: >
      docker run --name spark-worker
      -e ENABLE_INIT_DAEMON=false
      -e SPARK_MASTER_HOST='{{ hostvars[groups["master"][0]]["ansible_default_ipv4"]["address"] }}'
      -d
      popperized/spark-worker
- hosts: master
  tasks:
  - name: run benchmark
    shell: >
      docker run --rm --name spark-submit
      --entrypoint=/spark-bench/bin/spark-bench.sh
      popperized/spark-master /spark-bench/minimal.conf
  - name: run benchmark config A
    shell: >
      docker run --rm --name spark-configA
      --entrypoint=/spark-bench/bin/spark-bench.sh
      popperized/spark-master /spark-bench/classicA.conf
  - name: run benchmark config B
    shell: >
      docker run --rm --name spark-configB
      --entrypoint=/spark-bench/bin/spark-bench.sh
      popperized/spark-master /spark-bench/classicB.conf
