---
repetitions: 1
benchmarks:

- name: comd
  image: ivotron/comd:v1.1
  command: --xproc 2 --yproc 2 --zproc 1 --nx 64 --ny 64 --nz 64 --printRate 50 --nSteps 40
  environment:
    SINGLE_NODE: 1
    MPIRUN_FLAGS: -np 4
  cgroup_parent: /